
install gcc gsrc gcc6 and gcc7 in suse 11

# enable

```{r,eval=F}

vi ~/bin/enablegcc710.sh
chmod 755 ~/bin/enablegcc710.sh

#!/bin/bash -l
export LD_PRELOAD=" /home/ing/chen.zhao/usr/gsrc/gcc7/lib64/libstdc++.so.6.0.23 /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libgsl.so.19.3.0 "
export LD_LIBRARY_PATH=/home/ing/chen.zhao/usr/gsrc/gcc7/lib64:/home/ing/chen.zhao/usr/gsrc/gcc7/lib
export PATH=/home/ing/chen.zhao/usr/gsrc/gcc7/bin:/home/ing/chen.zhao/usr/bin:$PATH
export INCLUDE=/home/ing/chen.zhao/usr/gsrc/gcc7/include
export PKG_CONFIG_PATH=/home/ing/chen.zhao/usr/gsrc/gcc7/lib/pkgconfig:$PKG_CONFIG_PATH
export MANPATH=/home/ing/chen.zhao/usr/gsrc/gcc7/share/man:$MANPATH
export INFOPATH=/home/ing/chen.zhao/usr/gsrc/gcc7/share/info:$INFOPATH

#exec $SHELL -i

vi ~/.profile
alias enablegcc710='source ~/bin/enablegcc710.sh'


```

# best gsrc perfect configure without ada

```{r,eval=F}

# gsrc gcc6

unset LIBRARY_PATH CPATH C_INCLUDE_PATH PKG_CONFIG_PATH CPLUS_INCLUDE_PATH INCLUDE

export PATH=/usr/bin/:/home/ing/chen.zhao/usr/gnat/bin:/home/ing/chen.zhao/usr/bin:$PATH

cd ~/usr/gsrc/gcc6/gsrc
vi pkg/gnu/binutils/config.mk
--enable-gold
make -C pkg/gnu/binutils
make -C pkg/gnu/binutils install
export PATH=/home/ing/chen.zhao/usr/gsrc/gcc6/bin:$PATH

wget https://ftp.gnu.org/gnu/binutils/binutils-2.28.tar.gz
tar xzf binutils-2.28.tar.gz
cd binutils-2.28
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6 --enable-gold
make -j 8 && make install
cd ..

tar xzf ~/usr/src/cloog-0.18.0.tar.gz
wget http://isl.gforge.inria.fr/isl-0.16.tar.gz
tar xzf isl-0.16.tar.gz
cd isl-0.16
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6
make -j 8 && make install
cd ../cloog-0.18.0/
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6 --with-isl=/home/ing/chen.zhao/usr/gsrc/gcc6
make -j 8 && make install
cd ..

tar xJf ~/usr/src/gsrc/gcc5/gsrc/pkg/gnu/mpfr/download/mpfr-3.1.5.tar.xz
tar xf  ~/usr/src/gsrc/gcc5/gsrc/pkg/gnu/gmp/download/gmp-6.1.2.tar
tar xzf ~/usr/src/gsrc/gcc5/gsrc/pkg/gnu/mpc/download/mpc-1.0.3.tar.gz

cd gmp-6.1.2
./configure CFLAGS=-fPIC --enable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6
make -j 8 && make install
cd ../mpfr-3.1.5/
./configure CFLAGS=-fPIC --disable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6 --with-gmp=/home/ing/chen.zhao/usr/gsrc/gcc6
make -j 8 && make install
cd ../mpc-1.0.3/
./configure CFLAGS=-fPIC --disable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6 --with-gmp=/home/ing/chen.zhao/usr/gsrc/gcc6 --with-mpfr=/home/ing/chen.zhao/usr/gsrc/gcc6
make -j 8 && make install
cd ..
wget http://www.mr511.de/software/libelf-0.8.13.tar.gz
tar zxvf libelf-0.8.13.tar.gz
cd libelf-0.8.13
./configure CFLAGS=-fPIC --enable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc6
make -j 8 && make install
cd ..



wget http://www.mr511.de/software/libelf-0.8.13.tar.gz
tar zxvf libelf-0.8.13.tar.gz
cd libelf-0.8.13
./configure CFLAGS=-fPIC --enable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/versions/gcc-5.4.0
make -j 8 && make install
cd ..

vi pkg/gnu/gcc/config.mk

CONFIGURE_OPTS ?= \
 CFLAGS=-fPIC LD=/home/ing/chen.zhao/usr/gsrc/gcc6/bin/ld \
--enable-clocale=gnu \
--enable-cloog-backend=isl \
--enable-__cxa_atexit \
--enable-default-pie \
--enable-gold \
--enable-ld \
--enable-gnu-unique-object \
--enable-gtk-cairo \
--enable-languages=c,c++,fortran,go,lto,objc,obj-c++ \
--enable-libmpx \
--enable-libssp \
--enable-libstdcxx-debug \
--enable-libstdcxx-time=yes \
--enable-linker-build-id \
--enable-lto \
--disable-multiarch \
--disable-multilib  \
--enable-nls \
--enable-objc-gc=auto \
--enable-plugin \
--enable-shared \
--enable-threads=posix \
--with-system-zlib \
--with-target-system-zlib \
--with-gmp=/home/ing/chen.zhao/usr/gsrc/gcc6 \
--with-mpfr=/home/ing/chen.zhao/usr/gsrc/gcc6 \
--with-mpc=/home/ing/chen.zhao/usr/gsrc/gcc6 \
--with-libelf=/home/ing/chen.zhao/usr/gsrc/gcc6 \
--with-isl=/home/ing/chen.zhao/usr/gsrc/gcc6 \
--with-cloog=/home/ing/chen.zhao/usr/gsrc/gcc6 \
--with-binutils=/home/ing/chen.zhao/usr/gsrc/gcc6/bin \
--prefix=/home/ing/chen.zhao/usr/gsrc/gcc6

make -C pkg/gnu/gcc
make -j 8 -C pkg/gnu/gcc install
cd /home/ing/chen.zhao/usr/gsrc/gcc6/gsrc/pkg/gnu/gcc

LD_PRELOAD=" /home/ing/chen.zhao/usr/versions/gcc-6.3.0/lib/libisl.so.15.1.0 /home/ing/chen.zhao/usr/versions/gcc-6.3.0/lib/libgmp.so " \
make -j 8 -C work/gcc-6.3.0.build 

cd  work/gcc-6.3.0.build/
mkdir boehm-gc
cd boehm-gc
../../gcc-6.3.0/boehm-gc/configure
make -j 8
cd ../../../
cd work/gcc-6.3.0/boehm-gc/
./configure
cd -
cd work/gcc-6.3.0.build 
cp -rf boehm-gc/ x86_64-pc-linux-gnu/

LD_PRELOAD=" /home/ing/chen.zhao/usr/versions/gcc-6.3.0/lib/libisl.so.15.1.0 /home/ing/chen.zhao/usr/versions/gcc-6.3.0/lib/libgmp.so " \
make -j 8 


### gsrc gcc7


unset LIBRARY_PATH CPATH C_INCLUDE_PATH PKG_CONFIG_PATH CPLUS_INCLUDE_PATH INCLUDE

export PATH=/usr/bin/:/home/ing/chen.zhao/usr/gnat/bin:/home/ing/chen.zhao/usr/bin:$PATH

cd ~/usr/src/gsrc/gcc7/gsrc
vi pkg/gnu/binutils/config.mk
--enable-gold
make -C pkg/gnu/binutils
make -C pkg/gnu/binutils install
export PATH=/home/ing/chen.zhao/usr/gsrc/gcc7/bin:$PATH

wget https://ftp.gnu.org/gnu/binutils/binutils-2.28.tar.gz
tar xzf binutils-2.28.tar.gz
cd binutils-2.28
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7 --enable-gold
make -j 8 && make install
cd ..
export PATH=/home/ing/chen.zhao/usr/gsrc/gcc7/bin:$PATH

which ld

tar xzf ~/usr/src/cloog-0.18.0.tar.gz
wget http://isl.gforge.inria.fr/isl-0.16.tar.gz
tar xzf isl-0.16.tar.gz
cd isl-0.16
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7
make -j 8 && make install
cd ../cloog-0.18.0/
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7 --with-isl=/home/ing/chen.zhao/usr/gsrc/gcc7
make -j 8 && make install
cd ..

tar xJf ~/usr/src/gsrc/gcc5/gsrc/pkg/gnu/mpfr/download/mpfr-3.1.5.tar.xz
tar xf  ~/usr/src/gsrc/gcc5/gsrc/pkg/gnu/gmp/download/gmp-6.1.2.tar
tar xzf ~/usr/src/gsrc/gcc5/gsrc/pkg/gnu/mpc/download/mpc-1.0.3.tar.gz

cd gmp-6.1.2
./configure CFLAGS=-fPIC --enable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7
make -j 8 && make install
cd ../mpfr-3.1.5/
./configure CFLAGS=-fPIC --disable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7 --with-gmp=/home/ing/chen.zhao/usr/gsrc/gcc7
make -j 8 && make install
cd ../mpc-1.0.3/
./configure CFLAGS=-fPIC --disable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7 --with-gmp=/home/ing/chen.zhao/usr/gsrc/gcc7 --with-mpfr=/home/ing/chen.zhao/usr/gsrc/gcc7
make -j 8 && make install
cd ..
wget http://www.mr511.de/software/libelf-0.8.13.tar.gz
tar zxvf libelf-0.8.13.tar.gz
cd libelf-0.8.13
./configure CFLAGS=-fPIC --enable-shared --enable-static --prefix=/home/ing/chen.zhao/usr/gsrc/gcc7
make -j 8 && make install
cd ..


vi pkg/gnu/gcc/config.mk

CONFIGURE_OPTS ?= \
 CFLAGS=-fPIC LD=/home/ing/chen.zhao/usr/gsrc/gcc7/bin/ld \
--enable-clocale=gnu \
--enable-cloog-backend=isl \
--enable-__cxa_atexit \
--enable-default-pie \
--enable-gold \
--enable-ld \
--enable-gnu-unique-object \
--enable-gtk-cairo \
--enable-languages=c,c++,fortran,go,lto,objc,obj-c++ \
--enable-libmpx \
--enable-libssp \
--enable-libstdcxx-debug \
--enable-libstdcxx-time=yes \
--enable-linker-build-id \
--enable-lto \
--disable-multiarch \
--disable-multilib  \
--enable-nls \
--enable-objc-gc=auto \
--enable-plugin \
--enable-shared \
--enable-threads=posix \
--with-system-zlib \
--with-target-system-zlib \
--with-gmp=/home/ing/chen.zhao/usr/gsrc/gcc7 \
--with-mpfr=/home/ing/chen.zhao/usr/gsrc/gcc7 \
--with-mpc=/home/ing/chen.zhao/usr/gsrc/gcc7 \
--with-libelf=/home/ing/chen.zhao/usr/gsrc/gcc7 \
--with-isl=/home/ing/chen.zhao/usr/gsrc/gcc7 \
--with-cloog=/home/ing/chen.zhao/usr/gsrc/gcc7 \
--with-binutils=/home/ing/chen.zhao/usr/gsrc/gcc7/bin \
--prefix=/home/ing/chen.zhao/usr/gsrc/gcc7

LD_PRELOAD=" /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libisl.so.15.1.0 /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libgmp.so " \
make -C pkg/gnu/gcc

LD_PRELOAD=" /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libisl.so.15.1.0 /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libgmp.so " \
make -j 8 -C pkg/gnu/gcc install
cd pkg/gnu/gcc
LD_PRELOAD=" /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libisl.so.15.1.0 /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libgmp.so " \
make -j 8 -C work/gcc-7.1.0.build 

LD_PRELOAD=" /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libisl.so.15.1.0 /home/ing/chen.zhao/usr/gsrc/gcc7/lib/libgmp.so " \
make -j 8 -C work/gcc-7.1.0.build install

gcc/


```

# configure scl in suse; not work!!

all start from gcc

```{r,eval=F}

rm ~/chroot -rf

cd ~/usr/src
# install gcc

wget http://download.savannah.gnu.org/releases/lzip/lzip-1.18.tar.gz
#tar configure make install
wget http://isl.gforge.inria.fr/isl-0.18.tar.gz

## need old version; isl_band_member_is_zero_distance removed from 0.12
./configure --prefix=/home/ing/chen.zhao/usr/versions/isl/isl-0.11


wget https://repo.continuum.io/archive/Anaconda2-4.3.1-Linux-x86_64.sh

wget https://launchpad.net/bzrtools/stable/2.6.0/+download/bzrtools-2.6.0.tar.gz
wget https://launchpad.net/bzr/2.7/2.7.0/+download/bzr-2.7.0.tar.gz

wget https://www.bastoul.net/cloog/pages/download/count.php3?url=./cloog-0.18.4.tar.gz
# LD_LIBRARY_PATH=/home/ing/chen.zhao/usr/lib/:/home/ing/chen.zhao/usr/gsrc/lib/  ./configure --prefix=/home/ing/chen.zhao/usr/
wget https://www.bastoul.net/cloog/pages/download/cloog-0.18.0.tar.gz
# LD_LIBRARY_PATH=/home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/:/home/ing/chen.zhao/usr/gsrc/lib/  ./configure --prefix=/home/ing/chen.zhao/usr/versions/cloog/cloog-0.18.0
wget https://www.bastoul.net/cloog/pages/download/cloog-0.17.0.tar.gz
# LD_LIBRARY_PATH=/home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/:/home/ing/chen.zhao/usr/gsrc/lib/  ./configure --prefix=/home/ing/chen.zhao/usr/versions/cloog/cloog-0.17.0
wget http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
./configure --prefix=/home/ing/chen.zhao/usr/
wget https://github.com/GaloisInc/libdl/archive/master.zip


mkdir GSRC
cd ~/usr/src/GSRC

bzr checkout bzr://bzr.savannah.gnu.org/gsrc/trunk/ gsrc
cd ~/usr/src/GSRC/gsrc
./bootstrap                       # to create the configure script
./configure --prefix=/home/ing/chen.zhao/usr/gsrc/    # --prefix is directory to install the packages
bash ./setup.sh    

#source ~/usr/bin/enable.sh
#source ~/usr/bin/enable.gnat.sh

make -C pkg/gnu/hello
make -C pkg/gnu/hello install


make -j 8  -C pkg/gnu/binutils
make -j 8  -C pkg/gnu/binutils install

vi pkg/gnu/gcc/Makefile
gcc version as 4.9.4
vi pkg/gnu/gcc/config.mk
make -j 8  -C pkg/gnu/gcc

sha256sum ./pkg/gnu/gcc/download/gcc-4.9.4.tar.bz2 
sha256sum ./pkg/gnu/gcc/download/gcc-4.9.4.tar.bz2.sig

echo -e '6c11d292cd01b294f9f84c9a59c230d80e9e4a47e5c6355f046bb36d4f358092  download/gcc-4.9.4.tar.bz2' >> ./pkg/gnu/gcc/sha256sums
echo -e '0071e901d8706add63ad0d3a592e012eef2eadbd84b5b858e43ff62dd119328a  download/gcc-4.9.4.tar.bz2.sig' >> ./pkg/gnu/gcc/sha256sums

export PATH=/home/ing/chen.zhao/usr/bin:$PATH
export PATH=/home/ing/chen.zhao/usr/gnat/bin:$PATH
export PATH=/home/ing/chen.zhao/usr/gsrc/bin:$PATH

CFLAGS=" -L/home/ing/chen.zhao/usr/lib " make -j 8 -C pkg/gnu/gcc

CLOOGLIBS = /home/ing/chen.zhao/usr/versions/cloog/cloog-0.17.0/lib/libcloog-isl.a /home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/libisl.a  -L/home/ing/chen.zhao/usr/gnat/lib/ -lgnat_util -L/home/ing/chen.zhao/usr/gnat/lib/gcc/x86_64-pc-linux-gnu/4.9.4/rts-native/adalib/ -lgnat-2016  -L/home/ing/chen.zhao/usr/gnat/lib64/ -lgcc_s

vi /home/ing/chen.zhao/usr/src/GSRC/gsrc/pkg/gnu/gcc/work/gcc-4.9.4.build/gcc/Makefile

#CFLAGS=" -L/home/ing/chen.zhao/usr/lib -L/home/ing/chen.zhao/usr/gnat/lib64/ " 
make -j 8 -C pkg/gnu/gcc
LDFLAGS= -static-libstdc++ -static-libgcc 
CFLAGS= -g -L/home/ing/chen.zhao/usr/gsrc/lib /home/ing/chen.zhao/usr/versions/cloog/cloog-0.17.0/lib/libcloog-isl.a /home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/libisl.a  -L/home/ing/chen.zhao/usr/gnat/lib/ -lgnat_util -L/home/ing/chen.zhao/usr/gnat/lib/gcc/x86_64-pc-linux-gnu/4.9.4/rts-native/adalib/ -lgnat-2016  -L/home/ing/chen.zhao/usr/gnat/lib64/ -lgcc_s -ldl
CXXFLAGS= -g -L/home/ing/chen.zhao/usr/gsrc/lib /home/ing/chen.zhao/usr/versions/cloog/cloog-0.17.0/lib/libcloog-isl.a /home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/libisl.a  -L/home/ing/chen.zhao/usr/gnat/lib/ -lgnat_util -L/home/ing/chen.zhao/usr/gnat/lib/gcc/x86_64-pc-linux-gnu/4.9.4/rts-native/adalib/ -lgnat-2016  -L/home/ing/chen.zhao/usr/gnat/lib64/ -lgcc_s -ldl

## ./xgcc error
LD_LIBRARY_PATH=/home/ing/chen.zhao/usr/gnat/lib/:/home/ing/chen.zhao/usr/gnat/lib/gcc/x86_64-pc-linux-gnu/4.9.4/rts-native/adalib/ make -j 8 -C pkg/gnu/gcc

# make in build dir
# make install

### 4.9.4 success 

try 5.4.0

add /home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/libisl.a  /home/ing/chen.zhao/usr/versions/cloog/cloog-0.18.0/lib/libcloog-isl.a to 
g++  -o cc1  
add /home/ing/chen.zhao/usr/versions/cloog/cloog-0.17.0/lib/libcloog-isl.a /home/ing/chen.zhao/usr/versions/isl/isl-0.11/lib/libisl.a  -L/home/ing/chen.zhao/usr/gnat/lib/ -lgnat_util -L/home/ing/chen.zhao/usr/gnat/lib/gcc/x86_64-pc-linux-gnu/4.9.4/rts-native/adalib/ -lgnat-2016  

wget https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz --no-check-certificate
wget http://releases.llvm.org/4.0.0/llvm-4.0.0.src.tar.xz
tar xvpf llvm-4.0.0.src.tar.xz


#### good to go 

make -j 8  -C pkg/gnu/gcc



wget https://github.com/sclorg/scl-utils/archive/scl-1.zip
unzip scl-1
make 
cp scl ~/usr/bin



mkdir rpms
cd rpms
wget -np -r https://people.centos.org/tru/devtools-2/5/x86_64/RPMS/
cd ~/chroot/rpms/people.centos.org/tru/devtools-2/5/x86_64/RPMS/
wget ftp://ftp.icm.edu.pl/vol/rzm5/linux-scientificlinux/obsolete/59/x86_64/SL/libgomp-4.4.7-1.el5.x86_64.rpm

rpm -ivh --relocate /=/home/ing/chen.zhao/chroot devtoolset-2-gcc-4.8.2-15.el5.x86_64.rpm devtoolset-2-runtime-2.1-3.el5.noarch.rpm scl-utils-20120927-9.el5.x86_64.rpm libgomp-4.4.7-1.el5.x86_64.rpm devtoolset-2-binutils-2.23.52.0.1-10.el5.x86_64.rpm

wget ftp://ftp.icm.edu.pl/vol/rzm5/linux-scientificlinux/obsolete/5rolling/x86_64/SL/chkconfig-1.3.30.2-2.el5.x86_64.rpm
rpm2cpio chkconfig-1.3.30.2-2.el5.x86_64.rpm | sh -c 'cd ~/chroot && cpio -idmv --no-absolute-filenames'

rpm2cpio devtoolset-2-gcc-4.8.2-15.el5.x86_64.rpm devtoolset-2-runtime-2.1-3.el5.noarch.rpm scl-utils-20120927-9.el5.x86_64.rpm libgomp-4.4.7-1.el5.x86_64.rpm |   sh -c 'cd ~/chroot && cpio -idmv --no-absolute-filenames'

rpm2cpio devtoolset-2-binutils-2.23.52.0.1-10.el5.x86_64.rpm |   sh -c 'cd ~/chroot && cpio -idmv --no-absolute-filenames'

pwd /home/ing/chen.zhao/chroot
vi enable
export PATH=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root/usr/bin${PATH:+:${PATH}}
export MANPATH=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root/usr/share/man:$MANPATH
export INFOPATH=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root/usr/share/info${INFOPATH:+:${INFOPATH}}
export PCP_DIR=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root
# Some perl Ext::MakeMaker versions install things under /usr/lib/perl5
# even though the system otherwise would go to /usr/lib64/perl5.
export PERL5LIB=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root//usr/lib64/perl5/vendor_perl:/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root/usr/lib/perl5:/home/ing/chen.zhao/chroot/o
pt/rh/devtoolset-2/root//usr/share/perl5/vendor_perl${PERL5LIB:+:${PERL5LIB}}# bz847911 workaround:
# we need to evaluate rpm's installed run-time % { _libdir }, not rpmbuild time
# or else /etc/ld.so.conf.d files?
rpmlibdir=`rpm --eval "%{_libdir}"`
# bz1017604: On 64-bit hosts, we should include also the 32-bit library path.
if [ "$rpmlibdir" != "${rpmlibdir/lib64/}" ]; then
  rpmlibdir32=":/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root${rpmlibdir/lib64/lib}"
fi
export LD_LIBRARY_PATH=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root$rpmlibdir$rpmlibdir32${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
# duplicate python site.py logic for sitepackages
#pythonvers=`python -c 'import sys; print sys.version[:3]'`
#export PYTHONPATH=/opt/rh/devtoolset-2/root/usr/lib64/python$pythonvers/site-packages:/opt/rh/devtoolset-2/root/usr/lib/python$pythonvers/site-packages${PYTHONPATH:+:${PYTHONPATH}}
bash

cp enable  ~/usr/bin/enable.sh
chmod 755 ~/usr/bin/enable.sh

enable.sh

cd ~/usr/src
wget https://ftp.gnu.org/gnu/glibc/glibc-2.15.tar.gz

tar xzf glibc-2.15.tar.gz

mkdir build
cd build
../configure --prefix=/home/ing/chen.zhao/usr/ --localstatedir=/home/ing/chen.zhao/chroot/var
make -j 8 && make install

wget http://zlib.net/zlib-1.2.11.tar.gz
export LD_LIBRARY_PATH=/home/ing/chen.zhao/chroot/opt/rh/devtoolset-2/root/usr/lib64 
./configure --prefix=//home/ing/chen.zhao/usr/
make -j 8 && make install

wget ftp://share.sph.umich.edu/gotcloud/1.16/gotcloud-bin_1.16.tar.gz
export LD_PRELOAD=' /home/ing/chen.zhao/usr/lib/libc-2.15.so /home/ing/chen.zhao/usr/lib/libz.so.1.2.11 ' 



```
